### ISSUE TITLE
the tests are not runnable

### ISSUE THREAD

**Issue by martapanizzut** [a-kulkarn/pAdicSolver#1]
I tried to locally clone and use `pAdicSolver`, but there are multiple missing dependencies:
`AbstractAlgebra`, `Nemo` and `Hecke` , ... 
julia stopped depending on `REQUIRE` file a while ago -- it uses `Project.toml`.

I tried the following changes to make `include("./test/runtests.jl")` running:

```diff
diff --git a/src/AlgebraicSolvers/AlgebraicSolvers.jl b/src/AlgebraicSolvers/AlgebraicSolvers.jl
index 33a2863..3a40a0a 100644
--- a/src/AlgebraicSolvers/AlgebraicSolvers.jl
+++ b/src/AlgebraicSolvers/AlgebraicSolvers.jl
@@ -6,9 +6,10 @@ module AlgebraicSolvers
   using AbstractAlgebra
   using Nemo
   using Hecke
-  using Dory
+  using Main.Dory
 
   degree = DynamicPolynomials.maxdegree
+  monomials = DynamicPolynomials.monomials
 
   export coeftype
   coeftype(::Type{Polynomial{C, T}}) where {C, T} = T
diff --git a/test/runtests.jl b/test/runtests.jl
index 95fec3b..74e2c98 100644
--- a/test/runtests.jl
+++ b/test/runtests.jl
@@ -1,5 +1,6 @@
 
-include("../src/AlgebraicSolvers.jl")
+include("../src/Dory/Dory.jl")
+include("../src/AlgebraicSolvers/AlgebraicSolvers.jl")
 AS = Main.AlgebraicSolvers
 
 using LinearAlgebra
```

but I get ` LoadError: LoadError: MethodError: no method matching total_degree(::DynamicPolynomials.Polynomial{true,Float64})`.

It would be great if you could make it running, so I can try your package out :)

**Comment by a-kulkarn** [comment]
I've reorganized the repo so that it functions as a proper package. The tests have been updated as well.
